#pragma once
#include <Windows.h>
#define IOCTL_VM_START CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SVM_CONTROL CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_READ_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WRITE_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_READ_MSR CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WRITE_MSR CTL_CODE(FILE_DEVICE_UNKNOWN, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_TEST_THREAD CTL_CODE(FILE_DEVICE_UNKNOWN, 0x807, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SET_PROTECTED_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x808, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_FORCE_TERMINATE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x809, METHOD_BUFFERED, FILE_ANY_ACCESS)
typedef struct _SVM_RUN_CONTROL
{
	BOOLEAN Debug;
	BOOLEAN Unload;
}SVM_RUN_CONTROL, * PSVM_RUN_CONTROL;
typedef struct _READ_MEMORY_INFO
{
	PVOID Address;
	UINT64 OutputBufferSize;
	PVOID OutputBuffer;
}READ_MEMORY_INFO, * PREAD_MEMORY_INFO;
typedef struct _WRITE_MEMORY_INFO
{
	PVOID Address;
	UINT64 InputBufferSize;
	PVOID InputBuffer;
}WRITE_MEMORY_INFO, * PWRITE_MEMORY_INFO;
typedef struct _READ_MSR_INFO
{
	UINT32 Msr;
	UINT64 OutputValue;
}READ_MSR_INFO, * PREAD_MSR_INFO;
typedef struct _WRITE_MSR_INFO
{
	UINT32 Msr;
	UINT64 InputValue;
}WRITE_MSR_INFO, * PWRITE_MSR_INFO;